apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: /data
          name: simple-volume
  volumes:
    - name: simple-volume
      persistentVolumeClaim:
        claimName: simple-pvc